defaults:
  - _self_
  - environment: TwoArmTransport
  - policy: single_actor_critic
  - agent: single_agent
  - algorithm: ppo

environment:
  num_envs: 2

experiment:
  name: "single_agent_ppo"
  seed: 42
  total_timesteps: 1_000_000



#Custom Hydra run directory
hydra:
  run:
    dir: results/${hydra:runtime.choices.environment}/${hydra:runtime.choices.policies}/${now:%Y.%m.%d}