defaults:
  - _self_
  - environment: TwoArmLift
  - policy: TwoActorsSharedCritic
  - agent: SharedCritic
  - algorithm: MAPPO

seed: 42
total_timesteps: 1_000_000
exp_name: "two_actors_shared_critic"


#Custom Hydra run directory
hydra:
  run:
    dir: results/${hydra:runtime.choices.environment}/${hydra:runtime.choices.policy}/${now:%Y.%m.%d}