defaults:
  - _self_
  - environment: TwoArmTransport
  - policy: SingleActorCritic
  - agent: SingleAgent
  - algorithm: PPO


experiment:
  name: "single_agent_ppo"
  seed: 42
  total_timesteps: 1_000_000



#Custom Hydra run directory
hydra:
  run:
    dir: results/${hydra:runtime.choices.environment}/${hydra:runtime.choices.policy}/${now:%Y.%m.%d}